### ISSUE TITLE
Console.printLine in ModulePatternExample example not output

### ISSUE THREAD

**Issue by jamesboya** [Baeldung/scala-tutorials#1114]
This tutorial really help me to understand how to construct ZLayer code. However, seems that the Console.printLine in the Logging layer did not really output. Could I know whether I need further configuration?

https://github.com/Baeldung/scala-tutorials/blob/9ebfddefc9b4f0d625953ca0cd4255e54b332aaf/zio/src/main/scala-2/com/baeldung/scala/zio/ModulePatternExample.scala#L36

```
// build.sbt
val scala3Version = "3.3.1"

lazy val root = project
  .in(file("."))
  .settings(
    name := "foo",
    version := "0.1.0-SNAPSHOT",

    scalaVersion := scala3Version,

    libraryDependencies += "dev.zio" %% "zio" % "2.0.20",
    libraryDependencies += "org.scalameta" %% "munit" % "0.7.29" % Test
  )
```

**Comment by ulisseslima** [comment]
Hey, @jamesboya.

Please add a link to the tutorial you followed so we can take a look.

**Comment by jamesboya** [comment]
Hi, @ulisseslima,

I'm follow the GitHub link of [this tutorial](https://www.baeldung.com/scala/zio-intro). Then find out the example for [module pattern](https://github.com/Baeldung/scala-tutorials/blob/9ebfddefc9b4f0d625953ca0cd4255e54b332aaf/zio/src/main/scala-2/com/baeldung/scala/zio/ModulePatternExample.scala) with ZLayer.

**Comment by yadavan88** [comment]
Hi @jamesboya 
Thanks for reporting this. This was a regression while migrating to ZIO 2. We should have used `serviceWithZIO` instead of `serviceWith`. The code is fixed and all the logs are getting printed. 
[Here](https://github.com/Baeldung/scala-tutorials/blob/16eb011041fe87d480bd012764ea14579bfe142b/zio/src/main/scala/com/baeldung/scala/zio/ModulePatternExample.scala#L28) is the change.
